### ISSUE TITLE
Draw text on screen

### ISSUE THREAD

**Issue by dejan-xd** [dejan-xd/Chess_DSL#52]
Potrebno je implementirati funkcionalnost koja će ispisivati na ekranu tekst kao što je: "Checkmate", "Stalemate", "Black wins", "White wins" itd.

**Comment by jovan92** [comment]
Kroz ovaj issue je sređen bug  vezan za chess notation gde se + za in check i # za checkmate ponavljaju u nedogled, sada se ispisuje samo jednom. Takođe je rešen bug gde se game state objekat iznova kreira u input thread-u što je uzrokovalo da se pojavljuje flickering u vidu pomeranja figura i vraćanja na početnu poziciju.
