### ISSUE TITLE
Creating a graphic illustration of the project

### ISSUE THREAD

**Issue by nole23** [dejan-xd/Chess_DSL#7]
Potrebno je istraziti i uvezati neki od GUI bibilioteka sa projektom.

**Comment by dejan-xd** [comment]
Napravljen je initial GUI view main menu-ja. pygame je korišćen kao GUI biblioteka sa dodatkom pygame-widgets 0.6.1. Obe biblioteke su dodate u requirements.txt.

**Comment by dejan-xd** [comment]
Zatvaram issue
